default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5433") %>

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5